const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGUOT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',


    GET_POSTS: "GET_POSTS",
    GET_NEW_POSTS: "GET_NEW_POSTS",
    GET_POSTSLIMIT: "GET_POSTSLIMIT",
    EDIT_POST: "EDIT_POST",

    // user
    GET_CURRENT: 'GET_CURRENT',
    GET_USER: "GET_USER",
    EDIT_USER: 'EDIT_USER',

    //menu
    GET_MENU: "GET_MENU",
    GET_MENU_LIMIT: "GET_MENU_LIMIT",
    EDIT_MENU: 'EDIT_MENU',
    SAVEDATA: 'SAVEDATA',

    // order
    GET_ALL: 'GET_ALL',
    GET_ALLORDER: 'GET_ALLORDER',
    GET_ORDER: 'GET_ORDER',
    GET_ORDERMENU: 'GET_ORDERMENU',
    EDIT_BOOK: 'EDIT_BOOK',
    EDIT_TABLE: 'EDIT_TABLE',
    EDIT_BOOKMENU: 'EDIT_BOOKMENU',
    GET_TABLE: 'GET_TABLE',
    GET_STATISTICS: 'GET_STATISTICS',
    GET_STATISTICS_YEAR: 'GET_STATISTICS_YEAR',
}

export default actionTypes